
CIRCUIT_BREAKER_VARIATIONS = {
  TIME_BASED: 'time-based',
  COUNT_BASED: 'count-based'
};
module.exports = Object.freeze({
  BREAKER_STATE : {
    CLOSED: 'CLOSED',
    OPEN: 'OPEN',
    HALF_OPEN: 'HALF_OPEN',
  },
  DEFAULT_SUCCESS_THRESHOLD: 2,
  DEFAULT_FAILURE_THRESHOLD: 2,
  DEFAULT_TIMEOUT: 2000, // Timeout after which the state can be updated to HALF_OPEN
  RUNNER_TIMEOUT: 1000, // API runner timeout
  CIRCUIT_BREAKER_VARIATIONS,
  DEFAULT_CIRCUIT_BREAKER_VARIATION: CIRCUIT_BREAKER_VARIATIONS.COUNT_BASED,
  DEFAULT_TIMER_BASED_THRESHOLD: 5000,
});
